# Generated by Django 6.0 on 2026-01-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('pagado', 'Pagado'), ('vencido', 'Vencido'), ('anulado', 'Anulado')], default='activo', max_length=10),
        ),
    ]
