# Generated by Django 6.0 on 2025-12-21 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='fecha',
            field=models.DateField(),
        ),
    ]
